CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL UNIQUE,
    avatar VARCHAR(255),
    confirmed BOOLEAN NOT NULL DEFAULT FALSE
);
